[tool.poetry]
name = "mittleff"
version = "0.1.0"
description = ""
authors = ["Victor Santos (vct) <victor_santos@fisica.ufc.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scipy = "^1.11.2"
mpmath = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pandas = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
